# GitHub Sponsors configuration
# This file enables the "Sponsor" button on the repository

# GitHub Sponsors username
github: [w2csyh44qs-web]

# Uncomment and add other platforms as you set them up:
# patreon: your-username
# open_collective: your-project
# ko_fi: your-username
# tidelift: npm/package-name
# community_bridge: project-name
# liberapay: your-username
# issuehunt: your-username
# custom: ['https://yoursite.com/donate', 'https://yoursite.com/support']
